let items = {
  weapon: [
    {
      id: 0,
      name: "First knife",
      attack: [3],
      lvl: 1,
      // img: ,
      cost: 0,
    },
    {
      id: 1,
      name: "Pickaxe",
      attack: [4, 7],
      lvl: 1,
      // img: ,
      cost: 100,
    },
    {
      id: 2,
      name: "Basic sword",
      attack: [5, 8],
      lvl: 1,
      // img: ,
      cost: 130,
    },
    {
      id: 3,
      name: "Short sword",
      attack: [4, 9],
      lvl: 1,
      // img: ,
      cost: 130,
    },
    {
      id: 4,
      name: "Hand axe",
      attack: [7, 10],
      lvl: 2,
      // img: ,
      cost: 200,
    },
    {
      id: 5,
      name: "Hammer",
      attack: [5, 12],
      lvl: 2,
      // img: ,
      cost: 200,
    },
    {
      id: 6,
      name: "Mace",
      attack: [9, 11],
      lvl: 3,
      // img: ,
      cost: 230,
    },
    {
      id: 7,
      name: "Furry club",
      attack: [12, 13],
      lvl: 4,
      // img: ,
      cost: 350,
    },
    {
      id: 8,
      name: "Broadsword",
      attack: [10, 13],
      lvl: 4,
      // img: ,
      cost: 350,
    },
    {
      id: 9,
      name: "Silver mace",
      attack: [13, 17],
      lvl: 5,
      // img: ,
      cost: 390,
    },
    {
      id: 10,
      name: "Morning star",
      attack: [14, 15],
      lvl: 5,
      // img: ,
      cost: 390,
    },
    {
      id: 11,
      name: "Barbarian axe",
      attack: [16, 17],
      lvl: 6,
      // img: ,
      cost: 420,
    },
    {
      id: 12,
      name: "Sabre",
      attack: [17, 19],
      lvl: 7,
      // img: ,
      cost: 480,
    },
    {
      id: 13,
      name: "Epee",
      attack: [16, 21],
      lvl: 7,
      // img: ,
      cost: 500,
    },
    {
      id: 14,
      name: "Big sword",
      attack: [19, 20],
      lvl: 8,
      // img: ,
      cost: 600,
    },
    {
      id: 15,
      name: "Scimitar",
      attack: [13, 28],
      lvl: 9,
      // img: ,
      cost: 620,
    },
    {
      id: 16,
      name: "Warrior sabre",
      attack: [20],
      lvl: 9,
      // img: ,
      cost: 650,
    },
    {
      id: 17,
      name: "Warlord Sword",
      attack: [24],
      lvl: 10,
      // img: ,
      cost: 750,
    },
    {
      id: 18,
      name: "Halberd",
      attack: [22, 26],
      lvl: 10,
      // img: ,
      cost: 750,
    },
  ],
  shields: [
    {
      id: 19,
      name: "Wooden shield",
      type: "shield",
      defense: 4,
      lvl: 1,
      // img ,
      cost: 100,
    },
    {
      id: 20,
      name: "Viking shield",
      type: "shield",
      defense: 5,
      lvl: 1,
      // img ,
      cost: 130,
    },
    {
      id: 21,
      name: "Sentinel shield",
      type: "shield",
      defense: 7,
      lvl: 2,
      // img ,
      cost: 200,
    },
    {
      id: 22,
      name: "Brass shield",
      type: "shield",
      defense: 8,
      lvl: 3,
      // img ,
      cost: 250,
    },
    {
      id: 23,
      name: "Castle shield",
      type: "shield",
      defense: 10,
      lvl: 4,
      // img ,
      cost: 290,
    },
    {
      id: 24,
      name: "Steel shield",
      type: "shield",
      defense: 11,
      lvl: 5,
      // img ,
      cost: 350,
    },
    {
      id: 25,
      name: "Tower shield",
      type: "shield",
      defense: 13,
      lvl: 6,
      // img ,
      cost: 450,
    },
    {
      id: 26,
      name: "Knight shield",
      type: "shield",
      defense: 14,
      lvl: 7,
      // img ,
      cost: 520,
    },
    {
      id: 27,
      name: "Guardian shield",
      type: "shield",
      defense: 15,
      lvl: 7,
      // img ,
      cost: 600,
    },
    {
      id: 28,
      name: "Great shield",
      type: "shield",
      defense: 16,
      lvl: 9,
      // img ,
      cost: 650,
    },
    {
      id: 29,
      name: "Ultimate shield",
      type: "shield",
      defense: 18,
      lvl: 10,
      // img ,
      cost: 750,
    },
  ],
  secondWeapon: [
    {
      id: 30,
      name: "Knife",
      type: "second weapon",
      attack: [3, 5],
      lvl: 1,
      // img: ,
      cost: 100,
    },
    {
      id: 31,
      name: "Hunting knife",
      type: "second weapon",
      attack: [4, 6],
      lvl: 1,
      // img: ,
      cost: 150,
    },
    {
      id: 32,
      name: "Short axe",
      type: "second weapon",
      attack: [6, 9],
      lvl: 2,
      // img: ,
      cost: 200,
    },
    {
      id: 33,
      name: "Sharp axe",
      type: "second weapon",
      attack: [7, 9],
      lvl: 3,
      // img: ,
      cost: 250,
    },
    {
      id: 34,
      name: "Dager",
      type: "second weapon",
      attack: [8, 10],
      lvl: 4,
      // img: ,
      cost: 320,
    },
    {
      id: 35,
      name: "Poisoned knife",
      type: "second weapon",
      attack: [10, 11],
      lvl: 5,
      // img: ,
      cost: 350,
    },
    {
      id: 36,
      name: "Butcher knife",
      type: "second weapon",
      attack: [9, 16],
      lvl: 6,
      // img: ,
      cost: 420,
    },
    {
      id: 37,
      name: "Umbral mace",
      type: "second weapon",
      attack: [11, 14],
      lvl: 7,
      // img: ,
      cost: 500,
    },
    {
      id: 38,
      name: "Onyx Flail",
      type: "second weapon",
      attack: [14, 16],
      lvl: 8,
      // img: ,
      cost: 600,
    },
    {
      id: 39,
      name: "Brutal sword",
      type: "second weapon",
      attack: [15, 18],
      lvl: 9,
      // img: ,
      cost: 700,
    },
    {
      id: 40,
      name: "Assassin knife",
      type: "second weapon",
      attack: [17],
      lvl: 10,
      // img: ,
      cost: 750,
    },
  ],
};

export default items;
